//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18408
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Com.BitsQuan.Miscellaneous.SmsService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SmsService.Service1Soap")]
    public interface Service1Soap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllotAmount", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Com.BitsQuan.Miscellaneous.SmsService.ErrorResult AllotAmount(string accountid, string password, string childAccountId, int productId, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AllotAmount", ReplyAction="*")]
        System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.ErrorResult> AllotAmountAsync(string accountid, string password, string childAccountId, int productId, int amount);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_Submit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Com.BitsQuan.Miscellaneous.SmsService.CSubmitState g_Submit(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_Submit", ReplyAction="*")]
        System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.CSubmitState> g_SubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SubmitWithKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Com.BitsQuan.Miscellaneous.SmsService.CSubmitState g_SubmitWithKey(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SubmitWithKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.CSubmitState> g_SubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SchedulerSubmit", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Com.BitsQuan.Miscellaneous.SmsService.CSubmitState g_SchedulerSubmit(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SchedulerSubmit", ReplyAction="*")]
        System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.CSubmitState> g_SchedulerSubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SchedulerSubmitWithKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Com.BitsQuan.Miscellaneous.SmsService.CSubmitState g_SchedulerSubmitWithKey(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/g_SchedulerSubmitWithKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.CSubmitState> g_SchedulerSubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VersionInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string VersionInfo();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/VersionInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<string> VersionInfoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sm_GetRemain", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Com.BitsQuan.Miscellaneous.SmsService.CRemain Sm_GetRemain(string sname, string spwd, string scorpid, string sprdid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/Sm_GetRemain", ReplyAction="*")]
        System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.CRemain> Sm_GetRemainAsync(string sname, string spwd, string scorpid, string sprdid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        int ChangePassword(string account, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ChangePassword", ReplyAction="*")]
        System.Threading.Tasks.Task<int> ChangePasswordAsync(string account, string oldPassword, string newPassword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleInfoQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Com.BitsQuan.Miscellaneous.SmsService.SigleMsgInfo SingleInfoQuery(string accountId, string accountPassWord, string productextendId, string mobilePhone, string msgcontent, string startTime, string endTime, string pageSize, string curPage, string MsgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SingleInfoQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.SigleMsgInfo> SingleInfoQueryAsync(string accountId, string accountPassWord, string productextendId, string mobilePhone, string msgcontent, string startTime, string endTime, string pageSize, string curPage, string MsgID);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgPackageQueryWithKey", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Com.BitsQuan.Miscellaneous.SmsService.MsgPackageResult MsgPackageQueryWithKey(string accountid, string password, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgPackageQueryWithKey", ReplyAction="*")]
        System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.MsgPackageResult> MsgPackageQueryWithKeyAsync(string accountid, string password, string key);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgPackageQuery", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Com.BitsQuan.Miscellaneous.SmsService.MsgPackageResult MsgPackageQuery(string accountid, string password, string msgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgPackageQuery", ReplyAction="*")]
        System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.MsgPackageResult> MsgPackageQueryAsync(string accountid, string password, string msgid);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSplitCalculate", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        Com.BitsQuan.Miscellaneous.SmsService.MsgSplitCalculateResult MsgSplitCalculate(string accountId, string accountPassWord, string productextendId, uint mobilecount, string sms, uint mmslen);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/MsgSplitCalculate", ReplyAction="*")]
        System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.MsgSplitCalculateResult> MsgSplitCalculateAsync(string accountId, string accountPassWord, string productextendId, uint mobilecount, string sms, uint mmslen);
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(RemainResult))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class ErrorResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int errorCodeField;
        
        private string errorMsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ErrorCode {
            get {
                return this.errorCodeField;
            }
            set {
                this.errorCodeField = value;
                this.RaisePropertyChanged("ErrorCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorMsg {
            get {
                return this.errorMsgField;
            }
            set {
                this.errorMsgField = value;
                this.RaisePropertyChanged("ErrorMsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgSplitCalculateResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int resultCodeField;
        
        private string resultStateField;
        
        private uint pagesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int ResultCode {
            get {
                return this.resultCodeField;
            }
            set {
                this.resultCodeField = value;
                this.RaisePropertyChanged("ResultCode");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ResultState {
            get {
                return this.resultStateField;
            }
            set {
                this.resultStateField = value;
                this.RaisePropertyChanged("ResultState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public uint Pages {
            get {
                return this.pagesField;
            }
            set {
                this.pagesField = value;
                this.RaisePropertyChanged("Pages");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgPackageSingleInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int mobilePhonerQuantityField;
        
        private int chargeQuantityField;
        
        private int msgStateField;
        
        private int sendSuccessField;
        
        private int sendFailsField;
        
        private int sendFailTimesField;
        
        private int blackListsField;
        
        private int cancelsField;
        
        private int reportSuccessField;
        
        private int reportFailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int MobilePhonerQuantity {
            get {
                return this.mobilePhonerQuantityField;
            }
            set {
                this.mobilePhonerQuantityField = value;
                this.RaisePropertyChanged("MobilePhonerQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int ChargeQuantity {
            get {
                return this.chargeQuantityField;
            }
            set {
                this.chargeQuantityField = value;
                this.RaisePropertyChanged("ChargeQuantity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int MsgState {
            get {
                return this.msgStateField;
            }
            set {
                this.msgStateField = value;
                this.RaisePropertyChanged("MsgState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int SendSuccess {
            get {
                return this.sendSuccessField;
            }
            set {
                this.sendSuccessField = value;
                this.RaisePropertyChanged("SendSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public int SendFails {
            get {
                return this.sendFailsField;
            }
            set {
                this.sendFailsField = value;
                this.RaisePropertyChanged("SendFails");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public int SendFailTimes {
            get {
                return this.sendFailTimesField;
            }
            set {
                this.sendFailTimesField = value;
                this.RaisePropertyChanged("SendFailTimes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public int BlackLists {
            get {
                return this.blackListsField;
            }
            set {
                this.blackListsField = value;
                this.RaisePropertyChanged("BlackLists");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public int Cancels {
            get {
                return this.cancelsField;
            }
            set {
                this.cancelsField = value;
                this.RaisePropertyChanged("Cancels");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public int ReportSuccess {
            get {
                return this.reportSuccessField;
            }
            set {
                this.reportSuccessField = value;
                this.RaisePropertyChanged("ReportSuccess");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public int ReportFails {
            get {
                return this.reportFailsField;
            }
            set {
                this.reportFailsField = value;
                this.RaisePropertyChanged("ReportFails");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class MsgPackageResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error errorField;
        
        private MsgPackageSingleInfo[] resultField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Error error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public MsgPackageSingleInfo[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Error : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string erroridField;
        
        private string errormsgField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string errorid {
            get {
                return this.erroridField;
            }
            set {
                this.erroridField = value;
                this.RaisePropertyChanged("errorid");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string errormsg {
            get {
                return this.errormsgField;
            }
            set {
                this.errormsgField = value;
                this.RaisePropertyChanged("errormsg");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SingleResult : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string accountIdField;
        
        private string mobilePhoneField;
        
        private string msgContentField;
        
        private string productExtendIdField;
        
        private string resourceIdField;
        
        private string commitTimeField;
        
        private string sendStateField;
        
        private string reportStateField;
        
        private string departMentNameField;
        
        private string nameField;
        
        private string msgIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string AccountId {
            get {
                return this.accountIdField;
            }
            set {
                this.accountIdField = value;
                this.RaisePropertyChanged("AccountId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MobilePhone {
            get {
                return this.mobilePhoneField;
            }
            set {
                this.mobilePhoneField = value;
                this.RaisePropertyChanged("MobilePhone");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MsgContent {
            get {
                return this.msgContentField;
            }
            set {
                this.msgContentField = value;
                this.RaisePropertyChanged("MsgContent");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public string ProductExtendId {
            get {
                return this.productExtendIdField;
            }
            set {
                this.productExtendIdField = value;
                this.RaisePropertyChanged("ProductExtendId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string ResourceId {
            get {
                return this.resourceIdField;
            }
            set {
                this.resourceIdField = value;
                this.RaisePropertyChanged("ResourceId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string CommitTime {
            get {
                return this.commitTimeField;
            }
            set {
                this.commitTimeField = value;
                this.RaisePropertyChanged("CommitTime");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string SendState {
            get {
                return this.sendStateField;
            }
            set {
                this.sendStateField = value;
                this.RaisePropertyChanged("SendState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string ReportState {
            get {
                return this.reportStateField;
            }
            set {
                this.reportStateField = value;
                this.RaisePropertyChanged("ReportState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string DepartMentName {
            get {
                return this.departMentNameField;
            }
            set {
                this.departMentNameField = value;
                this.RaisePropertyChanged("DepartMentName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("Name");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public string MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
                this.RaisePropertyChanged("MsgID");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class SigleMsgInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private Error errorField;
        
        private SingleResult[] resultField;
        
        private int totlenumField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public Error error {
            get {
                return this.errorField;
            }
            set {
                this.errorField = value;
                this.RaisePropertyChanged("error");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public SingleResult[] result {
            get {
                return this.resultField;
            }
            set {
                this.resultField = value;
                this.RaisePropertyChanged("result");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int totlenum {
            get {
                return this.totlenumField;
            }
            set {
                this.totlenumField = value;
                this.RaisePropertyChanged("totlenum");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CRemain : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int stateField;
        
        private int remainField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public int Remain {
            get {
                return this.remainField;
            }
            set {
                this.remainField = value;
                this.RaisePropertyChanged("Remain");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class CSubmitState : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int stateField;
        
        private string msgIDField;
        
        private string msgStateField;
        
        private int reserveField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int State {
            get {
                return this.stateField;
            }
            set {
                this.stateField = value;
                this.RaisePropertyChanged("State");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string MsgID {
            get {
                return this.msgIDField;
            }
            set {
                this.msgIDField = value;
                this.RaisePropertyChanged("MsgID");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string MsgState {
            get {
                return this.msgStateField;
            }
            set {
                this.msgStateField = value;
                this.RaisePropertyChanged("MsgState");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int Reserve {
            get {
                return this.reserveField;
            }
            set {
                this.reserveField = value;
                this.RaisePropertyChanged("Reserve");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.18408")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class RemainResult : ErrorResult {
        
        private int remainField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Remain {
            get {
                return this.remainField;
            }
            set {
                this.remainField = value;
                this.RaisePropertyChanged("Remain");
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface Service1SoapChannel : Com.BitsQuan.Miscellaneous.SmsService.Service1Soap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1SoapClient : System.ServiceModel.ClientBase<Com.BitsQuan.Miscellaneous.SmsService.Service1Soap>, Com.BitsQuan.Miscellaneous.SmsService.Service1Soap {
        
        public Service1SoapClient() {
        }
        
        public Service1SoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1SoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Com.BitsQuan.Miscellaneous.SmsService.ErrorResult AllotAmount(string accountid, string password, string childAccountId, int productId, int amount) {
            return base.Channel.AllotAmount(accountid, password, childAccountId, productId, amount);
        }
        
        public System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.ErrorResult> AllotAmountAsync(string accountid, string password, string childAccountId, int productId, int amount) {
            return base.Channel.AllotAmountAsync(accountid, password, childAccountId, productId, amount);
        }
        
        public Com.BitsQuan.Miscellaneous.SmsService.CSubmitState g_Submit(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg) {
            return base.Channel.g_Submit(sname, spwd, scorpid, sprdid, sdst, smsg);
        }
        
        public System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.CSubmitState> g_SubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg) {
            return base.Channel.g_SubmitAsync(sname, spwd, scorpid, sprdid, sdst, smsg);
        }
        
        public Com.BitsQuan.Miscellaneous.SmsService.CSubmitState g_SubmitWithKey(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, string key) {
            return base.Channel.g_SubmitWithKey(sname, spwd, scorpid, sprdid, sdst, smsg, key);
        }
        
        public System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.CSubmitState> g_SubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sdst, string smsg, string key) {
            return base.Channel.g_SubmitWithKeyAsync(sname, spwd, scorpid, sprdid, sdst, smsg, key);
        }
        
        public Com.BitsQuan.Miscellaneous.SmsService.CSubmitState g_SchedulerSubmit(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg) {
            return base.Channel.g_SchedulerSubmit(sname, spwd, scorpid, sprdid, sbegindate, sdst, smsg);
        }
        
        public System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.CSubmitState> g_SchedulerSubmitAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg) {
            return base.Channel.g_SchedulerSubmitAsync(sname, spwd, scorpid, sprdid, sbegindate, sdst, smsg);
        }
        
        public Com.BitsQuan.Miscellaneous.SmsService.CSubmitState g_SchedulerSubmitWithKey(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg, string key) {
            return base.Channel.g_SchedulerSubmitWithKey(sname, spwd, scorpid, sprdid, sbegindate, sdst, smsg, key);
        }
        
        public System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.CSubmitState> g_SchedulerSubmitWithKeyAsync(string sname, string spwd, string scorpid, string sprdid, string sbegindate, string sdst, string smsg, string key) {
            return base.Channel.g_SchedulerSubmitWithKeyAsync(sname, spwd, scorpid, sprdid, sbegindate, sdst, smsg, key);
        }
        
        public string VersionInfo() {
            return base.Channel.VersionInfo();
        }
        
        public System.Threading.Tasks.Task<string> VersionInfoAsync() {
            return base.Channel.VersionInfoAsync();
        }
        
        public Com.BitsQuan.Miscellaneous.SmsService.CRemain Sm_GetRemain(string sname, string spwd, string scorpid, string sprdid) {
            return base.Channel.Sm_GetRemain(sname, spwd, scorpid, sprdid);
        }
        
        public System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.CRemain> Sm_GetRemainAsync(string sname, string spwd, string scorpid, string sprdid) {
            return base.Channel.Sm_GetRemainAsync(sname, spwd, scorpid, sprdid);
        }
        
        public int ChangePassword(string account, string oldPassword, string newPassword) {
            return base.Channel.ChangePassword(account, oldPassword, newPassword);
        }
        
        public System.Threading.Tasks.Task<int> ChangePasswordAsync(string account, string oldPassword, string newPassword) {
            return base.Channel.ChangePasswordAsync(account, oldPassword, newPassword);
        }
        
        public Com.BitsQuan.Miscellaneous.SmsService.SigleMsgInfo SingleInfoQuery(string accountId, string accountPassWord, string productextendId, string mobilePhone, string msgcontent, string startTime, string endTime, string pageSize, string curPage, string MsgID) {
            return base.Channel.SingleInfoQuery(accountId, accountPassWord, productextendId, mobilePhone, msgcontent, startTime, endTime, pageSize, curPage, MsgID);
        }
        
        public System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.SigleMsgInfo> SingleInfoQueryAsync(string accountId, string accountPassWord, string productextendId, string mobilePhone, string msgcontent, string startTime, string endTime, string pageSize, string curPage, string MsgID) {
            return base.Channel.SingleInfoQueryAsync(accountId, accountPassWord, productextendId, mobilePhone, msgcontent, startTime, endTime, pageSize, curPage, MsgID);
        }
        
        public Com.BitsQuan.Miscellaneous.SmsService.MsgPackageResult MsgPackageQueryWithKey(string accountid, string password, string key) {
            return base.Channel.MsgPackageQueryWithKey(accountid, password, key);
        }
        
        public System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.MsgPackageResult> MsgPackageQueryWithKeyAsync(string accountid, string password, string key) {
            return base.Channel.MsgPackageQueryWithKeyAsync(accountid, password, key);
        }
        
        public Com.BitsQuan.Miscellaneous.SmsService.MsgPackageResult MsgPackageQuery(string accountid, string password, string msgid) {
            return base.Channel.MsgPackageQuery(accountid, password, msgid);
        }
        
        public System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.MsgPackageResult> MsgPackageQueryAsync(string accountid, string password, string msgid) {
            return base.Channel.MsgPackageQueryAsync(accountid, password, msgid);
        }
        
        public Com.BitsQuan.Miscellaneous.SmsService.MsgSplitCalculateResult MsgSplitCalculate(string accountId, string accountPassWord, string productextendId, uint mobilecount, string sms, uint mmslen) {
            return base.Channel.MsgSplitCalculate(accountId, accountPassWord, productextendId, mobilecount, sms, mmslen);
        }
        
        public System.Threading.Tasks.Task<Com.BitsQuan.Miscellaneous.SmsService.MsgSplitCalculateResult> MsgSplitCalculateAsync(string accountId, string accountPassWord, string productextendId, uint mobilecount, string sms, uint mmslen) {
            return base.Channel.MsgSplitCalculateAsync(accountId, accountPassWord, productextendId, mobilecount, sms, mmslen);
        }
    }
}
